### ISSUE TITLE
QtQuick Not installed

### ISSUE THREAD

**Issue by Fardenz** [panagiotopoulos/MediaBar#1]
I am receiving this error while I click on the tray bar icon
![image](https://user-images.githubusercontent.com/28675332/81089982-5d375980-8efd-11ea-9ea9-63cf74699cee.png)

`Error loading QML file: file:///home/javi/.local/share/plasma/plasmoids/org.kde.mediabar/contents/ui/main.qml:20:1: module "QtQuick" version 2.13 is not installed`

**Comment by elybin** [comment]
i'm pretty sure the error is here 

https://github.com/panagiotopoulos/MediaBar/blob/f1ea86c86df96a05404c3cc58893add55a06222d/contents/ui/main.qml#L20
doing little bit research, i found that your` /contens/ui/` missing some file called `main.qmlc`. idk what it is, not solved yet, just guessing. 
i found another extension that working on my kubuntu 18.

**org.kde.mediabar**
![image](https://user-images.githubusercontent.com/4969689/81498961-19c05f00-92f2-11ea-89ab-216547296d48.png)

![image](https://user-images.githubusercontent.com/4969689/81498995-555b2900-92f2-11ea-87bd-1dae41ce4ff5.png)

**Comment by elybin** [comment]
i found another information https://stackoverflow.com/questions/35349997/module-qtquick-version-2-5-is-not-installed maybe helps. 

waiting some solution, awesome app!

**Comment by panagiotopoulos** [comment]
Seems like you had an older version of Qt installed. Released a new version with a lower version requirement (Qt 5.12 LTS and up).
